### ISSUE TITLE
BIN filename for CHEETAH V2.2

### ISSUE THREAD

**Issue by lanpartyceo** [Lebensgefahr/kingroon_kp3s_pro_v2#1]
Hello,

Was unsure how else to pass on this information.
In the intro, you have written that the filename for the V2.2 board is unknown. 

I have found out that it is the following:

CHEETAH_V2_2.bin

Hopefully this is helpful. Your information sure has been. I am in the process of trying the update (unsuccessfully) the V2.2 board.

**Comment by Lebensgefahr** [comment]
Thanks a lot you are the first one how did that :-) I assumed this name, but can't check.
I will update readme asap.

**Comment by Lebensgefahr** [comment]
> Hopefully this is helpful. Your information sure has been. I am in the process of trying the update (unsuccessfully) the V2.2 board.

Why it is unsuccessfully? Can I help?

**Comment by lanpartyceo** [comment]
To your first question:

I asked the seller, and they asked the technician and gave me the answer. I
can confirm when flashing a new .bin it flashes and the file is renamed to
.cur so i assume it has taken it.

To the second, i no longer can see the mcu via usb on the board. I built
armbian and have the image on a 2nd emmc module, but when i build using
your mcu settings, and use usb it does not come visible to any OS. So i
know the flash is wrong. I have tried many different permeutations of
bootloader size but to no effect.

Looking at the V2.2 board, i can see a 12hz chip next to a usb controller
chip, but ibhave also had no luck with using the 12hz clock either.

**Comment by Lebensgefahr** [comment]
> To the second, i no longer can see the mcu via usb on the board. I built armbian and have the image on a 2nd emmc module, but when i build using your mcu settings, and use usb it does not come visible to any OS. So i know the flash is wrong. I have tried many different permeutations of bootloader size but to no effect.

Did you try another boot loader offset? When I tried to flash I use 28 but with no luck. As I have full mcu flash dump I can calculate it. When offset is wrong file processed but mcu is not booting. Try 28 (or others it can't damage it).

**Comment by Lebensgefahr** [comment]
In addition try to disable SWD pins it can use them for USB for example. Try different combinations offset/swd.

**Comment by Lebensgefahr** [comment]
I forget. You can check current bulid settings in klippy.log in string like "Loaded" if some of the pins are enabled it will be written in that string.
```
Loaded MCU 'mcu' 105 commands (v0.11.0-122-ge6ef48cd-dirty-20230330_000318-mkspi / gcc: (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907] binutils: (2.31.1-12+11) 2.31.1)
MCU 'mcu' config: ADC_MAX=4095 BUS_PINS_i2c1=PB6,PB7 BUS_PINS_i2c1a=PB8,PB9 BUS_PINS_i2c2=PB10,PB11 BUS_PINS_spi1=PA6,PA7,PA5 BUS_PINS_spi1a=PB4,PB5,PB3 BUS_PINS_spi2=PB14,PB15,PB13 BUS_PINS_spi3=PB4,PB5,PB3 CLOCK_FREQ=72000000 MCU=stm32f103xe PWM_MAX=255 RECEIVE_WINDOW=192 RESERVE_PINS_serial=PA10,PA9 SERIAL_BAUD=250000 STATS_SUMSQ_BASE=256 STEPPER_BOTH_EDGE=1
```

**Comment by Lebensgefahr** [comment]
> I have tried many different permeutations of bootloader size but to no effect.

This is about boo tloader offset. I understood, sry ;-) Anyway you can check current settings in klippy.log.
Did you try to find something in dmesg/lsusb?
You can build an old image.

**Comment by Lebensgefahr** [comment]
> I have tried many different permeutations of bootloader size but to no effect.

Actually it is not about bootloader size. It is about where bootloader can find firmware image first block. In this case bootloader size is about 16kb but it is trying to find application image at 32kb.

**Comment by lanpartyceo** [comment]
I understand. I do have the klippy.log file and that data, which confirms USB for the MCU from when it was working, but the backup of the bootloader i thought i had was not what i thought so i have no way of restoring it to operation to re-check dmesg. 

I plugged in the old emmc module to check the dmesg data there from when it was working, was not able to locate anything useful that i could tell.

MY stlink cable should be arriving tomorrow, but without the origional mcu flash dump from the v2.2 board i cant restore to working.

I have an excel sheet going with Bootloader size | clock| SWD and am working through the possible permeutations, but so far no 16/28/32 combo has worked in 8 or 12 clock speed.

**Comment by lanpartyceo** [comment]
> I forgot. You can check current bulid settings in klippy.log in string like "Loaded" if some of the pins are enabled it will be written in that string.
> 
> ```
> Loaded MCU 'mcu' 105 commands (v0.11.0-122-ge6ef48cd-dirty-20230330_000318-mkspi / gcc: (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907] binutils: (2.31.1-12+11) 2.31.1)
> MCU 'mcu' config: ADC_MAX=4095 BUS_PINS_i2c1=PB6,PB7 BUS_PINS_i2c1a=PB8,PB9 BUS_PINS_i2c2=PB10,PB11 BUS_PINS_spi1=PA6,PA7,PA5 BUS_PINS_spi1a=PB4,PB5,PB3 BUS_PINS_spi2=PB14,PB15,PB13 BUS_PINS_spi3=PB4,PB5,PB3 CLOCK_FREQ=72000000 MCU=stm32f103xe PWM_MAX=255 RECEIVE_WINDOW=192 RESERVE_PINS_serial=PA10,PA9 SERIAL_BAUD=250000 STATS_SUMSQ_BASE=256 STEPPER_BOTH_EDGE=1
> ```

Mine: 
Loaded MCU 'mcu' 105 commands (v0.11.0-122-ge6ef48cd-dirty-20230817_150801-mkspi / gcc: (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907] binutils: (2.31.1-12+11) 2.31.1)
MCU 'mcu' config: ADC_MAX=4095 BUS_PINS_i2c1=PB6,PB7 BUS_PINS_i2c1a=PB8,PB9 BUS_PINS_i2c2=PB10,PB11 BUS_PINS_spi1=PA6,PA7,PA5 BUS_PINS_spi1a=PB4,PB5,PB3 BUS_PINS_spi2=PB14,PB15,PB13 BUS_PINS_spi3=PB4,PB5,PB3 CLOCK_FREQ=72000000 MCU=stm32f103xe PWM_MAX=255 RESERVE_PINS_USB=PA11,PA12 STATS_SUMSQ_BASE=256 STEPPER_BOTH_EDGE=1

**Comment by Lebensgefahr** [comment]
> Mine:

And it is default usb pins RESERVE_PINS_USB=PA11,PA12.
And you tried different bootloader offset. Interesting.
It is possible to build default image from commit with hash e6ef48cdf7b7e23f422cbe0ec46091001b840674 it is v0.11.0-122 (122 commit from tag).
SWD pins are not disabled as I can see in your log. And settings are almost default. You just need to experiment with different offset size. Did you clean your sd card every time after successful flashing?

**Comment by lanpartyceo** [comment]
> > Mine:
> 
> And it is default usb pins RESERVE_PINS_USB=PA11,PA12. And you tried different bootloader offset. Interesting. It is possible to build default image from commit with hash e6ef48cdf7b7e23f422cbe0ec46091001b840674 it is v0.11.0-122 (122 commit from tag). SWD pins are not disabled as I can see in your log. And settings are almost default. You just need to experiment with different offset size. Did you clean your sd card every time after successful flashing?

Yep, saw the pin confirmation. Also didn't think SWD was on so that is good verification.

No, i did not clean the Sd card every time. with previous printers i have not had issue wit that, but can give that a go here.

I will have to put the stock flashed emmc back and try to build from there and see if she will take. I will be able to do that about 5 hours or so from now.

Thanks for the tips. we'll see.

**Comment by Lebensgefahr** [comment]
> Yep, saw the pin confirmation. Also didn't think SWD was on so that is good verification.
> 
> No, i did not clean the Sd card every time. with previous printers i have not had issue wit that, but can give that a go here.
> 
> I will have to put the stock flashed emmc back and try to build from there and see if she will take. I will be able to do that about 5 hours or so from now.
> 
> Thanks for the tips. we'll see.

I tried to disable SWD pins and it has confirmation in log as i can remember. So it is not disabled (there is no message about that).
At least you need to remove .CUR file as I know. Otherwise bootloader will not use .BIN file. It is protection in case of flashing every time when printer turned on with sd card inserted. I have some issues with updating mcu like that. Put file on sd card turn it on but it was not updated. Just repeat the process with copying file again.

**Comment by Lebensgefahr** [comment]
> > > Mine:
> > 
> > 
> > And it is default usb pins RESERVE_PINS_USB=PA11,PA12. And you tried different bootloader offset. Interesting. It is possible to build default image from commit with hash e6ef48cdf7b7e23f422cbe0ec46091001b840674 it is v0.11.0-122 (122 commit from tag). SWD pins are not disabled as I can see in your log. And settings are almost default. You just need to experiment with different offset size. Did you clean your sd card every time after successful flashing?
> 
> Yep, saw the pin confirmation. Also didn't think SWD was on so that is good verification.
> 
> No, i did not clean the Sd card every time. with previous printers i have not had issue wit that, but can give that a go here.
> 
> I will have to put the stock flashed emmc back and try to build from there and see if she will take. I will be able to do that about 5 hours or so from now.
> 
> Thanks for the tips. we'll see.

And don't forget to wait about 30-40 seconds after you turned it off. SSH is available about 20 seconds after printer was turned off. That means power supply still giving energy from capacitors. :-)

**Comment by lanpartyceo** [comment]
> At least you need to remove .CUR file as I know. Otherwise bootloader will not use .BIN file. It is protection in case of flashing every time when printer turned on with sd card inserted. I have some issues with updating mcu like that. Put file on sd card turn it on but it was not updated. Just repeat the process with copying file again.
> 

I always removed the .cur file when replacing the bin. I use the reset button on the board to reset the mcu after sd card insertion, and then wait about 30 seconds, remove sd card (and return to USB reader for next round :) ) and reset mcu with the button again. Nothing ever appears back in lsusb ("watch -n 0.5 lsusb" in a seperate ssh window), whether i reset with button or do a full shutdown and re-power.

On the clock reference, how is this determined? I thought it was determined by the silver chip somewhere on the board with the frequency printed on it. Is that correct? Is the chip in the same location on the v2 vs v2.2?

**Comment by Lebensgefahr** [comment]
> I always removed the .cur file when replacing the .bin. I use the reset button on the board to reset the mcu after sd card insertion, and then wait about 30 seconds, remove sd card (and return to USB reader for next round :) ) and reset mcu with the button again. Nothing ever appears back in lsusb ("watch -n 0.5 lsusb" in a seperate ssh window), whether i reset with button or do a full shutdown and re-power. After each attempt, the sd card has a .cur file, indicating it took that latest .bin file.
Ah it ok. Just need to be sure :-) I saw reset button but don't use it.


> On the clock reference, how is this determined? I thought it was determined by the silver chip somewhere on the board with the frequency printed on it. Is that correct? Is the chip in the same location on the v2 vs v2.2?
It is correct but not in this case :-) In most cases mcu has embedded oscillator. As I know it is 8 Mhz and it is used.
V2.2 plate has the same chip GD32F303VET6 at the same place as V2.0
https://github.com/Lebensgefahr/kingroon_kp3s_pro_v2?tab=readme-ov-file#difference-between-v2-hardware

**Comment by Lebensgefahr** [comment]
> I use the reset button on the board to reset the mcu

Which button?
MCU-RST?
https://github.com/Lebensgefahr/kingroon_kp3s_pro_v2/blob/main/pictures/diff/MB2.2.jpg

**Comment by lanpartyceo** [comment]
> > I use the reset button on the board to reset the mcu

> MCU-RST


Yes, that button

**Comment by lanpartyceo** [comment]
> > > I use the reset button on the board to reset the mcu
> 
> > MCU-RST
> 
> 
> Yes, that button
> 

Just as the SCB_RST would power cycle the whole board (or at least just the sbc side) the mcu does juat the mcu. It beeps to lwt you know it reset. Just wanted to be clear on my method in case i was wrong, but i figured that would be fastest  while watching lsusb to see if it reappeared to the OS.

**Comment by Lebensgefahr** [comment]
> > > > I use the reset button on the board to reset the mcu
> > 
> > 
> > > MCU-RST
> > 
> > 
> > Yes, that button
> 
> Just as the SCB_RST would power cycle the whole board (or at least just the sbc side) the mcu does juat the mcu. It beeps to lwt you know it reset. Just wanted to be clear on my method in case i was wrong, but i figured that would be fastest while watching lsusb to see if it reappeared to the OS.

Didn't see SCB_RST button :-) Only SOC_RST.
Your method looks most preferred. I used this method with THR plate.

**Comment by Lebensgefahr** [comment]
> > > > I use the reset button on the board to reset the mcu
> > 
> > 
> > > MCU-RST
> > 
> > 
> > Yes, that button
> 
> Just as the SCB_RST would power cycle the whole board (or at least just the sbc side) the mcu does juat the mcu. It beeps to lwt you know it reset. Just wanted to be clear on my method in case i was wrong, but i figured that would be fastest while watching lsusb to see if it reappeared to the OS.

But sometimes THR file in /dev/serial/by-id/ wasn't appear and I need to turn the printer off again or reset it again.

**Comment by lanpartyceo** [comment]
> 
> Didn't see SCB_RST button :-) Only SOC_RST. 

^ I'm gonna have to call that one a, uh.........memory error :)

> Your method looks most preferred. I used this method with THR plate.

Thanks. good to know it "should" work.

Will be able to give a go again in a few hours. gonna try getting the v11 .bin rebuilt and see if any luck there where v12 isn't having it, yet.

**Comment by Lebensgefahr** [comment]
> Will be able to give a go again in a few hours. gonna try getting the v11 .bin rebuilt and see if any luck there where v12 isn't having it, yet.

How is it going? :-)

**Comment by lanpartyceo** [comment]
> > Will be able to give a go again in a few hours. gonna try getting the v11 .bin rebuilt and see if any luck there where v12 isn't having it, yet.
> 
> How is it going? :-)

No luck with any of the offet sizes. The mcu still did not come back online.

I did not enable the extra options to be changed, since i was leaving the default usb and clock settings anyway.

**Comment by Lebensgefahr** [comment]
> > > Will be able to give a go again in a few hours. gonna try getting the v11 .bin rebuilt and see if any luck there where v12 isn't having it, yet.
> > 
> > 
> > How is it going? :-)
> 
> No luck with any of the offet sizes. The mcu still did not come back online.
> 
> I did not enable the extra options to be changed, since i was leaving the default usb and clock settings anyway.

Maybe something wrong with mcu or SoC. In this situation only st-link can help to recognize chip state. If it is THR than I know two cases when SoC was burned out by disconnecting THR plate under voltage. But mcu can't be disconnected.

**Comment by lanpartyceo** [comment]
> > > > Will be able to give a go again in a few hours. gonna try getting the v11 .bin rebuilt and see if any luck there where v12 isn't having it, yet.
> > > 
> > > 
> > > How is it going? :-)
> > 
> > No luck with any of the offet sizes. The mcu still did not come back online.
> > 
> > I did not enable the extra options to be changed, since i was leaving the default usb and clock settings anyway.
> 
> Maybe something wrong with mcu or SoC. In this situation only st-link can help to recognize chip state. If it is THR than I know two cases when SoC was burned out by disconnecting THR plate under voltage. But mcu can't be disconnected.

Yeah, i think it should still be okay, doesnt make sense it would burn out.

As a test, i flashed a 32kb offset with it set to can on the same PA#'s and the port speet to the same as they have on /etc/network/interfaces.d/can0 in case this was used and not a leftover from v2 or used for the rp2040. It didnt like that and beeped once a sec till i reflashed a 32kb with usb poet to it. 

So it seems right, it just won't reconnect

**Comment by Lebensgefahr** [comment]
> As a test, i flashed a 32kb offset with it set to can on the same PA#'s and the port speet to the same as they have on /etc/network/interfaces.d/can0 in case this was used and not a leftover from v2 or used for the rp2040. It didnt like that and beeped once a sec till i reflashed a 32kb with usb poet to it.
> 
> So it seems right, it just won't reconnect

It can be a proof that 32kb bootloader offset is correct. At this moment you know exactly which compiling settings should be used. Maybe you can try to turn printer off/on completely. Did you see something about mcu USB device in dmesg? It can be hotplug issue for example. 
It works before you started updating there is a little chance of damage it with this activity.
Is mcu unavailable with an old emmc now? Did you try to build firmware from commit i posted earlier?

**Comment by lanpartyceo** [comment]
> > As a test, i flashed a 32kb offset with it set to can on the same PA#'s and the port speet to the same as they have on /etc/network/interfaces.d/can0 in case this was used and not a leftover from v2 or used for the rp2040. It didnt like that and beeped once a sec till i reflashed a 32kb with usb poet to it.
> > So it seems right, it just won't reconnect
> 
> It can be a proof that 32kb bootloader offset is correct. At this moment you know exactly which compiling settings should be used. Maybe you can try to turn printer off/on completely. Did you see something about mcu USB device in dmesg? It can be hotplug issue for example. It works before you started updating there is a little chance of damage it with this activity. Is mcu unavailable with an old emmc now? Did you try to build firmware from commit i posted earlier?


That's exactly what i was working on, the old emmc. and lo and behold, i just turned it on this morning to restart testing, and up she boots fully!

I guess you were right before when you said i needed to leave it for 60 seconds un-powered completely to discharge. 

This confirms that my way of using the mcu-reset button, while fine to load the new firmware, is not good for then booting up the new firmware. it must be un-powered and loose all charge to come back properly

**Comment by Lebensgefahr** [comment]
Did you mean it is updated successfully? Congratulations!!!
For example when you turning printer off THR losing power at this moment but rockchip still processing about next 20 sec. So it seams enough to restart THR only but in fact i've encountered situation where it's device doesn't appear. I can't explain it and can only guess. USB plug has +5V and GND pins larger than others. In situation when we turn printer off it looks like a normal disconnecting (without disconnecting data pins). But when we turn printer on it is already connected by D+D- and power pins are connecting secondly.

**Comment by lanpartyceo** [comment]
> Did you mean it is updated successfully? Congratulations!!!

Thanks! And thanks for the help and confirmations. Now that i have it back to V11, i can work on V12 again and be assured on how to make it stick.

> For example when you turning printer off THR losing power at this moment but rockchip still processing about next 20 sec. So it seams enough to restart THR only but in fact i've encountered situation where it's device doesn't appear. I can't explain it and can only guess. USB plug has +5V and GND pins larger than others. In situation when we turn printer off it looks like a normal disconnecting (without disconnecting data pins). But when we turn printer on it is already connected by D+D- and power pins are connecting secondly.

After that it is onto the THR board and soldering on the USB connection to be able to flash it.

**Comment by lanpartyceo** [comment]
Perfect. I have everything flashed to v12 now!

I'll grab the extra screens and different steps and you can add in the data to your guide if you want. then it will be a compete guide :D for these machines

**Comment by Lebensgefahr** [comment]
> steps later to

Thanks a lot. I'll be waiting.

**Comment by lanpartyceo** [comment]
Alright, here we go.

For the mcu:
The config i have pictured below. Instructions are the same as yours( with the .bin name being different if doing the flash to sd card while it is in the printer method you have listed). Emphasis on making sure to completely shutdown the system and wait 15-60 seconds before powering back up after flashing the new firmware.

For the rp2040:
Guidelines: the connector area is JST-XH 2.5mm(2.54mm). Pins can be attached from a female jst plug if the pins are pushed all the way through and the plug used to hold them in place while soldering. Remove female end completely after soldering to have accessible pins (shown in rp2040 picture) Male JST end needs to be attached to a doner USB cable from an old mouse or micro-usb cable.

Building the firmware:
1. generate firmware using the image guidelines
2. in the 'klipper/out' folder a 'klipper.uf2' file will be generated.
3. Move the klipper.uf2 file to your pc for later transfer.

Flashing:
1. Solder pins to the rp2040 board.
4. Build usb cable.
5. Connect USB cable to rp2040 (5V to 5V, G to G, Data + to Data +, Data - to Data -)
6. While holding down the "boot" button on the rp2040, plug in the USB cable to any PC that will automount a USB drive for you to access the files (Windows, Ubuntu Desktop, MAC, etc)
7. If done and wired correctly, a drive names "RP1-RP2" will be connected.
8. Copy the klipper.uf2 file to the "RP1=-RP2" drive"
9. The rp2040 will immediately reboot itself and load the new firmware as soon as the file transfer is complete. This is normal.
10. Wait 30 seconds, then unplug the rp2040 and reinstall in the printer.

Here is the `make menuconfig` screen for the MCU:
![V2 2_klipper_mcu_settings](https://github.com/Lebensgefahr/kingroon_kp3s_pro_v2/assets/1388519/6c0b69f0-b0d6-4995-8b75-a37704ae7cd9)

Here is the same for the rp2040:
![V2 2_klipper_rp2040_settings](https://github.com/Lebensgefahr/kingroon_kp3s_pro_v2/assets/1388519/9a59e6ba-d23e-4d1a-b378-d359677e2db7)

Here is the rp2040 helpful image:
![V2 2_rp2040_1](https://github.com/Lebensgefahr/kingroon_kp3s_pro_v2/assets/1388519/191c232b-9077-4535-a6e1-654748136ad0)

Example shot of USB Cable with JST-XH connector:
![V2 2_rp2040_cable_1](https://github.com/Lebensgefahr/kingroon_kp3s_pro_v2/assets/1388519/d3e98334-52dc-4b8e-866a-206ad423b28f)

Here is an example shot of the female JST-XH connector prepped for pin stabilization & donation:
![V2 2_female_JST-XH_doner_pins_example](https://github.com/Lebensgefahr/kingroon_kp3s_pro_v2/assets/1388519/616cc4aa-8c91-49e5-8c42-c597f2ff65b2)

Let me know if you need any clarification in any areas.

**Comment by Lebensgefahr** [comment]
Thanks a lot. I will add your clarifications asap.
BTW rp2040 can be flashed by make command. It still working but it's necessary to make clean before execute it.
Thanks for your cooperation.
