### ISSUE TITLE
Kingroon KLP1 Compatibility

### ISSUE THREAD

**Issue by XxyZwW** [Lebensgefahr/kingroon_kp3s_pro_v2#2]
Hi, I have a Kingroon KLP1 with a Cheetah 2.2 motherboard and THR v2, can this guide help me to be able to update the armbian image as well, and if so, is there anything I should consider replacing?

**Comment by Lebensgefahr** [comment]
Hello. It is absolutely the same. There is no difference between KLP1 and KP3S Pro V2 as I know. It uses the same parts. Just pay attention to communication between THR and main board MCU with the main board.
