### ISSUE TITLE
PI-TS35 V1

### ISSUE THREAD

**Issue by willngton** [Lebensgefahr/kingroon_kp3s_pro_v2#4]
Good day, 

Thanks for your work, I would like to know if by any chance you have tested with MLC PI-TS35

I tried and getting only screen as bellow.

Any tip on how can I make it work 

Thank you!

![thumbnail](https://github.com/user-attachments/assets/013b88e8-9cc5-4173-b36c-32e27fbf9dea)

**Comment by Lebensgefahr** [comment]
> > Hi. I don't have any screen except monochrome display connected to MCU of my printer. Mabye you need to use KlipperScreen (can be installed with Kiauh).
> 
> Thanks for the reply,
> 
> I did install Klipperscreen but image would be the same and no touch working.
> 
> Will try check dtb files and compare with MKS,

You can try to use dtb file from platform where your display is working. Kp3s pro v2 is close to mkspi. Dtb file in my image (if you are using it) is differ from rockchip default which is appear during build image process. As I remember wifi is not appear with it. You can replace this file with yours and reboot the system. In case it will work you can unpack dtb file merge it and pack again.

**Comment by Lebensgefahr** [comment]
I didn't know that it should work as in youtube video posted by Kingroon. So in this case it should works too.
I removed some patches from the image related to hdmi only.
Maybe it is KlipperScreen starting issue. I will compare this part of original image soon or you can do it yourself.

**Comment by Lebensgefahr** [comment]
> Good day,
> 
> Thanks for your work, I would like to know if by any chance you have tested with MLC PI-TS35
> 
> I tried and getting only screen as bellow.
> 
> Any tip on how can I make it work
> 
> Thank you!
> 
> ![thumbnail](https://private-user-images.githubusercontent.com/5961905/385008277-013b88e8-9cc5-4173-b36c-32e27fbf9dea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MTU3ODAsIm5iZiI6MTczMTUxNTQ4MCwicGF0aCI6Ii81OTYxOTA1LzM4NTAwODI3Ny0wMTNiODhlOC05Y2M1LTQxNzMtYjM2Yy0zMmUyN2ZiZjlkZWEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMTYzMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQyZGMzOTUwNjMxNDM0NGY2ZWJkMGNhNWEzZmNlZGRlOGFlYjRiMzI5YThmMTZlNWRlNzQ5ODUzNDhkMDEzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kqeU9CcXrE65CFBfBla9whlP8hcXkgXyXB6nVbitJg4)

Try to install KlipperScreen with kiauh. It is warning that X server and a lot of dependencies will be installed.
Warning:
> It will create a service, enable boot to console and install the graphical dependencies.
boot to console is all you need as your screen is working.
